# pytest.ini
[pytest]
markers =
    smoke: Тесты для быстрой проверки (smoke-тесты)
    regression: Тесты для регрессионного тестирования
    api: Тесты API
    db: Тесты с проверкой БД
    critical: Критичные тесты
    user: Тесты пользователей
    movie: Тесты фильмов